name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Runs only when you push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & push Backend
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hms-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/hms-backend:${{ github.sha }}

      # Step 4: Build & push Frontend
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hms-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/hms-frontend:${{ github.sha }}
